[project]
name = "workout-tracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "alembic==1.18.3",
    "asyncio>=4.0.0",
    "fastapi>=0.128.6",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.40.0",
]
